#!/bin/sh

E_BADARGS=65
E_BACKEND=66

if [ $# -eq 0 ]
then
  echo "=============== Welcome to the Sphere SDK ==============="
  echo "Usage:"
  echo "  to create a project:         `basename $0` new [project-name]"
  echo "  to create a sample project:  `basename $0` quickstart"
  echo "========================================================="
  exit $E_BADARGS
fi
if [ $1 == "quickstart" ]
then
  echo "Setting up a sample project on the backend."
  json=`curl -silent -d "" http://localhost:4242/bootstrap/cars`
  if [ $? -ne 0 ]
  then
    exit $E_BACKEND
  fi

  cp -r templates/sphere-quickstart .
  cd sphere-quickstart

  projectKey=`echo $json | sed 's/.*"projectKey":"\([^"]*\)".*/\1/g'`
  clientId=`echo $json | sed 's/.*"clientId":"\([^"]*\)".*/\1/g'`
  clientSecret=`echo $json | sed 's/.*"clientSecret":"\([^"]*\)".*/\1/g'`

  echo "Updating project config."
  rndAppSecret1=`head -c20 /dev/urandom | md5`  # 32 chars
  rndAppSecret2=`head -c20 /dev/urandom | md5`  # 32 chars
  rndAppSecret=$rndAppSecret1$rndAppSecret2     # app secret has to be 64 chars
  sed -i.bak "s/{{projectKey}}/$projectKey/g;s/{{clientId}}/$clientId/g;s/{{clientSecret}}/$clientSecret/g;s/{{appSecret}}/$rndAppSecret/g" conf/application.conf
  rm conf/application.conf.bak

  echo "Starting local server on port 9000."
  #play run
else
  echo "Not supported yet. Check out '`basename $0` quickstart'."
fi