on:
  - workflow_dispatch
#  - pull_request
  - push

name: CI

jobs:

  integrationTest:
    name: "Integration tests"

    runs-on: ubuntu-latest

    env:
      JVM_SDK_IT_CLIENT_ID: ${{ secrets.JVM_SDK_IT_CLIENT_ID }}
      JVM_SDK_IT_CLIENT_SECRET: ${{ secrets.JVM_SDK_IT_CLIENT_SECRET }}
      JVM_SDK_IT_PROJECT_KEY: ${{ secrets.JVM_SDK_IT_PROJECT_KEY }}
      JVM_SDK_IT_SCOPES: ${{ secrets.JVM_SDK_IT_SCOPES }}
      JVM_SDK_IT_AUTH_URL: ${{ secrets.JVM_SDK_IT_AUTH_URL }}
      JVM_SDK_IT_API_URL: ${{ secrets.JVM_SDK_IT_API_URL }}
      JVM_SDK_IT_OAUTH_CLIENT_ID: ${{ secrets.JVM_SDK_IT_CLIENT_ID }}
      JVM_SDK_IT_OAUTH_CLIENT_SECRET: ${{ secrets.JVM_SDK_IT_CLIENT_SECRET }}
      JVM_SDK_IT_OAUTH_PROJECT_KEY: ${{ secrets.JVM_SDK_IT_PROJECT_KEY }}
      JVM_SDK_IT_OAUTH_SCOPES: ${{ secrets.JVM_SDK_IT_SCOPES }}
      JVM_SDK_IT_OAUTH_AUTH_URL: ${{ secrets.JVM_SDK_IT_AUTH_URL }}
      JVM_SDK_IT_OAUTH_API_URL: ${{ secrets.JVM_SDK_IT_API_URL }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Cache maven repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Setup java"
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - run: mvn clean install javadoc:aggregate -DskipTests --no-transfer-progress -Pjavadoc-jdk-8u121,third-party-licenses
      - run: mvn exec:java -pl commercetools-internal-docs -Dexec.mainClass="introspection.rules.RulesMain" -Dexec.classpathScope="test"
      - run: mvn exec:java -pl commercetools-models -Dexec.mainClass="io.sphere.sdk.client.MainMethodThreadLeakTest" -Dexec.classpathScope="test"
      - run: mvn test verify --no-transfer-progress -Djava.util.logging.config.file=src/test/resources/logging.properties

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'licenses/*'
          disable_globbing: true
          commit_message: "Update licenses"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
