on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        default: MINOR
        options:
          - MAJOR
          - MINOR
          - PATCH

name: Release

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Cache maven repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Setup java"
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - run: scripts/setup-signing-key.sh
        env:
          DECRYPTER: ${{ secrets.DECRYPTER }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

#      - run: ./prepare-release.sh ${{ github.event.inputs.release_type }} ${{ github.ref_name }}
